-- This file is automatically generated by the baba mod manager.
-- it's wise not to touch it unless something is awry.

-- This name will be replaced by a function call to the mod's folder.
-- if it says "__ name __" (without spaces) then something has gone wrong
if __name__ then
    __name__()
end
